export const buttons = [
  { value: "AC" },
  { value: "+/-" },
  { value: "%" },
  { value: "/", isOrange: true },
  { value: "7" },
  { value: "8" },
  { value: "9" },
  { value: "*", isOrange: true },
  { value: "4" },
  { value: "5" },
  { value: "6" },
  { value: "-", isOrange: true },
  { value: "1" },
  { value: "2" },
  { value: "3" },
  { value: "+", isOrange: true },
  { value: "☀️/🌙" },
  { value: "0" },
  { value: "," },
  { value: "=", isOrange: true },
];
